export const POEMS = [{
        id: 'weight-of-pixels',
        title: 'the weight of pixels',
        poet: 'Ahmed',
        tag: 'digital',
        excerpt: 'i built a house from light, but the shadows moved in first.',
        lines: [
            'i built a house from light,',
            'but the shadows moved in first.',
            '',
            'every window was a screen,',
            'every door, a loading bar.',
            '',
            'i hung pictures of places',
            'i had only visited in tabs.',
            '',
            'the neighbors were cached versions',
            'of people i used to know —',
            'rendered wrong,',
            'always slightly out of date.',
            '',
            'still, i stayed.',
            'the resolution was familiar.',
            'and familiar is',
            'its own kind of warmth.',
        ],
    },
    {
        id: '404',
        title: '404',
        poet: 'Ahmed',
        tag: 'loss',
        excerpt: 'you searched for me in all the wrong URLs.',
        lines: [
            'you searched for me',
            'in all the wrong URLs.',
            '',
            'i was cached somewhere',
            'between your last tab',
            'and the one you forgot to close.',
            '',
            'maybe you typed my name wrong.',
            'maybe the server was down.',
            'maybe you just',
            'stopped refreshing.',
            '',
            'either way —',
            'page not found.',
            '',
            'and the internet',
            'kept spinning',
            'like it always does.',
        ],
    },
    {
        id: 'soft-crash',
        title: 'soft crash',
        poet: 'Ahmed',
        tag: 'night',
        excerpt: 'the system went down at 3am on a tuesday.',
        lines: [
            'the system went down',
            'at 3am on a tuesday.',
            '',
            'nobody noticed',
            'except the moon,',
            '',
            'who had been watching',
            'my blinking cursor all night.',
            '',
            'she said nothing.',
            'she never does.',
            '',
            'but she dimmed a little,',
            'like she understood',
            'the specific grief',
            'of unsaved work.',
            '',
            'i closed the laptop.',
            'opened the window.',
            'let the cool air debug me.',
        ],
    },
    {
        id: 'bandwidth',
        title: 'bandwidth',
        poet: 'Ahmed',
        tag: 'connection',
        excerpt: 'we had infinite connection but limited bandwidth.',
        lines: [
            'we had infinite connection',
            'but limited bandwidth.',
            '',
            'so we compressed our feelings',
            'into tiny, lossy packets',
            'and hoped they\'d arrive intact.',
            '',
            'sometimes they didn\'t.',
            'sometimes a whole sentence',
            'would arrive as a single emoji,',
            'misread and moved on from.',
            '',
            'we blamed the network.',
            'we blamed the distance.',
            'we blamed the algorithm',
            'for burying what mattered.',
            '',
            'but i think',
            'we were just afraid',
            'of the full-quality version',
            'of ourselves.',
        ],
    },
    {
        id: 'ghost-mode',
        title: 'ghost mode',
        poet: 'Ahmed',
        tag: 'solitude',
        excerpt: 'i turned on ghost mode and watched the world keep moving.',
        lines: [
            'i turned on ghost mode',
            'and watched the world keep moving.',
            '',
            'nobody noticed.',
            'the timeline filled itself.',
            'the stories expired.',
            '',
            'i was there —',
            'present but undetected,',
            'like a zero-day in the code of the party.',
            '',
            'i read your messages',
            'without the blue ticks.',
            'i laughed at the memes',
            'without the like.',
            '',
            'it felt like power, briefly.',
            'then it felt like glass.',
            '',
            'transparent.',
            'cold.',
            'and very easy to break.',
        ],
    },
    {
        id: 'signal-loss',
        title: 'signal loss',
        poet: 'Ahmed',
        tag: 'distance',
        excerpt: 'three dots appeared. then nothing. then three dots again.',
        lines: [
            'three dots appeared.',
            'then nothing.',
            'then three dots again.',
            '',
            'i refreshed the conversation',
            'like weather apps in summer —',
            'obsessively,',
            'and still surprised',
            'when nothing changed.',
            '',
            'you were typing something.',
            'or erasing something.',
            'or erasing me.',
            '',
            'eventually the dots stopped.',
            'eventually i did too.',
            '',
            'and the chat stayed open',
            'like a window in winter —',
            'letting in nothing',
            'but the cold.',
        ],
    },
];